### PR TITLE
Add required dependencies to README

### PR DESCRIPTION
**Pull request by Hofer-Julian**
- slqx-cli
- postgresql-client
- libssl-dev on Ubuntu

### CODE REVIEW

**Review by LukeMathWalker — APPROVED** [review]

**Comment by LukeMathWalker** [comment]
Can you move sqlx-cli to the non-OS specific section of the requirements?

**Comment by Hofer-Julian** [comment]
> Can you move sqlx-cli to the non-OS specific section of the requirements?

How about I add it to all OS sections?

Otherwise the order might be confusing since it doesn’t compile e.g. on Ubuntu without libssl-dev

**Comment by LukeMathWalker** [comment]
That's fair, let's add it to all OSes sections.

**Comment by Hofer-Julian** [comment]
Done!

**Comment by LukeMathWalker** [comment]
Thank you!

**Pull request merged**
