### PR TITLE
feat: fix issue install on ubuntu

### PR DESCRIPTION
**Pull request by Lantianyou**

### CODE REVIEW

**Comment by Lantianyou** [comment]
image
Having trouble installing `sqlx-cli` in my ubuntu machine, copied the recommended installing script from crates.io. I am new to rust, so not sure if doing so will cause compatibility in the future. 

Thank you for your course, excited to learn!

**Comment by LukeMathWalker** [comment]
Hey!
From the screenshot it looks like you are trying to install the wrong version (0.5.5 instead of 0.5.7).

**Comment by Lantianyou** [comment]
Hi

I am using the

**Comment by Lantianyou** [comment]
Hi 
Actually it is here to instruct me to do so.

image

**Comment by Lantianyou** [comment]
You can checkout the file changed section to see detail :)

**Comment by LukeMathWalker** [comment]
Uh, that's a relic from a very old version. It should be enough to patch it to 0.5.7 from 0.5.5.

**Pull request closed without merging**
